### ISSUE TITLE
The function AuthenticationBasic make a little mistake.

### ISSUE THREAD

**Issue by towerbit** [ngraziano/SharpRTSP#100]
Login failed for

Line 18 in file AuthenticationBasic.cs
`            return $"Bassic {Convert.ToBase64String(Encoding.UTF8.GetBytes(usernamePasswordHash))}";
`

It should be
`            return $"Basic {Convert.ToBase64String(Encoding.UTF8.GetBytes(usernamePasswordHash))}";
`

Anyway, thanks a lot for this wonderful project.

**Comment by ngraziano** [comment]
Thanks for the find
