### ISSUE TITLE
Keepalives need to reauthenticate for some servers.

### ISSUE THREAD

**Issue by bentorkington** [ngraziano/SharpRTSP#126]
An RTSPServer may require reauthentication after a time. The Axis M5525 camera in particular has been found to reject `GET_PARAMETER` keepalives after 150 seconds, by responding with a `401 Unauthorized` and a new nonce value.

Rather than stop at this point, the RTSPClient should send another authentication using the new nonce.

[PR #125](https://github.com/ngraziano/SharpRTSP/pull/125)

**Comment by ngraziano** [comment]
PR merged.
Please close if it solve the issue.
