### ISSUE TITLE
RTSP Redirect

### ISSUE THREAD

**Issue by lehne** [ngraziano/SharpRTSP#14]
I want to set up an RTSP redirect only so I can use a different url for the streams such as rtsp://streams.something.com:554/stream1 will redirect to rtsp://232.232.54.23/stream1. Does this library support such a scenario or can that be accomplished with a web server?

**Comment by RogerHardiman** [comment]
I think the library can be expanded to achieve this.
There are .cs files for each message type and the REDIRECT message will need to be added.
Then you need to make a small program to act as a server and process incoming messages and generate a REDIRECT reply.

So it will need a bit of programming.

**Comment by nfteamo** [comment]
i have the same problem,somebody can help?
