### ISSUE TITLE
NuGet Support?

### ISSUE THREAD

**Issue by kinetiq** [ngraziano/SharpRTSP#17]
Surprised this project doesn't have it, is there some reason?

**Comment by ngraziano** [comment]
No particular reason for no support of nuget. Just lack of time.

Patch are welcome.

**Comment by ITSharkz** [comment]
@ngraziano will be great, after 5 years. 
Your library works on newest .Net which is kind of awesome.

**Comment by ngraziano** [comment]
I take a little time to publish on nuget (a version more modern) : https://www.nuget.org/packages/SharpRTSP

**Comment by winkmichael** [comment]
Thank you for creating the NuGet package and for maintaining this project
