### ISSUE TITLE
How to get frame from RTSP stream?

### ISSUE THREAD

**Issue by OlesjaPakhomova** [ngraziano/SharpRTSP#19]
Good afternoon! 
How to create bitmap from an array byte?
I tried to get using this method from the project. No result.
 // Output an array of NAL Units.
        // One frame of video may encoded in 1 large NAL unit, or it may be encoded in several small NAL units.
        // This function writes out all the NAL units that make one frame of video.
        // This is done to make it easier to feed H264 decoders which may require all the NAL units for a frame of video at the same time.

        // When writing to a .264 file we will add the Start Code 0x00 0x00 0x00 0x01 before each NAL unit
        // when outputting data for H264 decoders, please note that some decoders require a 32 bit size length header before each NAL unit instead of the Start Code
        private void Output_NAL(List<byte[]> nal_units)
        {
            if (fs == null) return; // check filestream initialised

            int bytes_written = 0;

            foreach (byte[] nal_unit in nal_units)
            {
                fs.Write(new byte[] { 0x00, 0x00, 0x00, 0x01 }, 0, 4);  // Write Start Code
                fs.Write(nal_unit, 0, nal_unit.Length);           // Write NAL
                              bytes_written += (nal_unit.Length + 4);
            }
            fs.Flush(true);
        }

**Comment by ngraziano** [comment]
Hi,
This library do not handle the decoding of the video. You will only get compressed video stream. To do the decoding you must use a library like FFMPEG.

**Comment by flysunshine** [comment]
how can i use the FFMPEG library to decode the video in C#? I found most of it in C/C++。

**Comment by RogerHardiman** [comment]
I do not have any examples of calling FFMPEG from C#
