### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by Razgort** [ngraziano/SharpRTSP#2]
Hi,
Do you plan to add any documentation or implementation example ?

**Comment by RogerHardiman** [comment]
You can find documentation for an RTSP Client which can connect to an IP camera and write the video as a .264 file (for ffplay or vlc or mplayer) on my fork of this project at https://github.com/RogerHardiman/SharpRTSP

**Comment by RogerHardiman** [comment]
Update - my changes with sample documentation and an example have been merged into the main git project so no need to look at my fork now.

I think we can close this Issue down now.

**Comment by ngraziano** [comment]
merge request #4 add doc
