### ISSUE TITLE
Is it supports Backchannel audio sending to camera?

### ISSUE THREAD

**Issue by SamRizvi** [ngraziano/SharpRTSP#21]
Is it supports Backchannel audio sending to camera?.

It will be great if you could provide me code snippets or samples for the same.

**Comment by ngraziano** [comment]
There is no specific support for back channel but i think the main component are here to try to set this kind of communication.

I have no hardware that support this kind of audio backchannel I can not try.

**Comment by SamRizvi** [comment]
I have a device with me. But i dont have any clue on how to proceed with. So if you have a code snippet for that I will check it and get back to you.

**Comment by RogerHardiman** [comment]
I've implemented audio (G711 protocol) in the normal direction (Camera to Viewer)
Can you test this.
I can then have a look at the back channel.

**Comment by RogerHardiman** [comment]
Never heard back from the original poster if the forward channel G711 worked so closing this down
