### ISSUE TITLE
HOW can i send the whole NAL. With RTP over UDP by Fragmenting the NAL.?

### ISSUE THREAD

**Issue by flysunshine** [ngraziano/SharpRTSP#22]
i see this in your code"send the whole NAL. With RTP over RTSP we do not need to Fragment the NAL (as we do with UDP packets or Multicast)",
   and i do not quite understand, can you help me out please?thanks !

**Comment by ngraziano** [comment]
In TCP the fragmentation of the NAL is done at the network level. 
In UDP the size is limited by the MTU (generaly 1500 byte for the wole packet) so we need to fragment the NAL.

**Comment by flysunshine** [comment]
thank you very much，can this project be used in monitoring system? I am a student,trying to do something about remote monitor with your project,and how can i do that? hope you can help me ,thanks very much.

**Comment by flysunshine** [comment]
and how can i decode the video  with C# in time？(with FFMPEG?) i search a lot,and find nothing .really looking foward to your answer.

**Comment by RogerHardiman** [comment]
decoding the compressed video stream back to images that can be displayed on a screen is outside the scope of this library. 
But as a summary, there are lots of ways to do it and for H264 video the process is
a) Initialise FFMPEG and pass in the SPS, PPS and the NALs
b) On Apple you can use a VTDecompressionSession
c) On Android you can use MediaCodec
d) there are Windows APIs too

Unfortunately that is all beyond what we can do in this library.
