### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by farzad-kafami** [ngraziano/SharpRTSP#24]
Hi 
in my camera setup I have an option "Enable RTSP connection without authentication" when enable this option program runs correctly but when disable DESCRIBE message return 401 code ("Unauthorized")
how can I set UserName and Password in commands?

**Comment by ngraziano** [comment]
Hi,

The authentication is not included in the library, you will have to add it manually. 
In RTSP authentication is same as HTTP one. There is chance that authentication is "Basic" one for your camera, other type may be more complicated.

You may have to use this kind of code for each packet:
```csharp
string username = "Your username";
string password = "Your password";

string svcCredentials = Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes(username + ":" + password));

describe_message.Headers.Add("Authorization", "Basic " + svcCredentials);
```

**Comment by farzad-kafami** [comment]
thanks for answer but my camera authentication is Digest access authentication
I solve that

**Comment by RogerHardiman** [comment]
I have added Digest Authentication in a Pull Request for the RTSP Client example
