### ISSUE TITLE
How to handle mjpeg RTSP stream?

### ISSUE THREAD

**Issue by dxball** [ngraziano/SharpRTSP#27]
I got a mjpeg rtsp stream. How can I extract and export the frame data?

the sdp data of the stream
```
v=0
o=- 11814266 1 IN IP4 192.168.1.169
s=RTSP/RTP stream from IPNC
i=mjpeg
t=0 0
a=tool:LIVE555 Streaming Media v2015.08.07
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:RTSP/RTP stream from IPNC
a=x-qt-text-inf:mjpeg
m=video 0 RTP/AVP 26
c=IN IP4 0.0.0.0
b=AS:12000
a=control:track1
```

**Comment by RogerHardiman** [comment]
I have never tried a MPJEG stream.
I have made some changes in the RTSPClient example that will allow you to receive RTP packets for MJPEG (Payload Type 26) but you will need to write your own code to take each RTP frame and extract the JPEG data. The RFC for JPEG over RTP tells you how to do this.
It would be great if you could implement this and we can merge your code into the project.

**Comment by dxball** [comment]
I will try it, thank you!

**Comment by RogerHardiman** [comment]
The latest version of the RTSP Client Example in GitHub will connect to a MJPEG RTSP stream and receive the RTP packets.
However the code will soon arrive at this section
```
                else if (rtp_payload_type == 26) {
                    Console.WriteLine("No parser for JPEG RTP packets");

```
and this is where you need to write some software to take the RTP packets and extract the JPEGs from them. There is a RFC standard that defines how to do this.

**Comment by RogerHardiman** [comment]
closing this issue down. If someone wants to write the code to extract the JPEGs from a MJPEG stream then we can include it
