### ISSUE TITLE
can use this project for audio file transfer

### ISSUE THREAD

**Issue by tahana** [ngraziano/SharpRTSP#29]
can use this project for audio file with g711 format transfer?

**Comment by RogerHardiman** [comment]
It can be used but will need some extra functions implementing.
The main RTSP and RTP transfer code is all in SharpRTSP.
But neither @ngraziano or me have written the code to pack G711 into RTP packets.

If you wanted to do this I'd help you as much as possible.

**Comment by RogerHardiman** [comment]
I've added in G711 support to the sample RtspClient test program.
It receives the G711 audio (mu-Law or A-Law / PCMU or PCMA) from the RTSP server and writes it to disk.
