### ISSUE TITLE
Features and possibilities

### ISSUE THREAD

**Issue by alexsandro-xpt** [ngraziano/SharpRTSP#3]
With this library, can I streamming a mp3 file to HTML5 player via rtp/rtsp protocol?

**Comment by RogerHardiman** [comment]
As far as know, HTML5 video and audio players do not use RTP/RTSP.

**Comment by alexsandro-xpt** [comment]
@RogerHardiman So, how streamming content are played on web browser without flash?

**Comment by RogerHardiman** [comment]
As far as i know all the web browser based streaming solutions that are HTML5 based (and do not use plugins) use protocols that work via HTTP Proxies.

Some systems use WebRTC protocol which sends the video data via WebSockets.
WebSockets is a two way socket from the browser to a server that will pass through HTTP proxies.

Some systems have Javascript video codecs but still use WebSockets to get the raw video over a websockets connection.

Some systems use HLS which is a standard for streaming over HTTP

**Comment by RogerHardiman** [comment]
I think we could close this issue.
