### ISSUE TITLE
Can you help me in extending to get the eventId,endOfEvent,reserved,volume,eventduration fields

### ISSUE THREAD

**Issue by TryyingToCode** [ngraziano/SharpRTSP#31]
I see in the RTSP Client Example
We can extend the following part 
private void Rtsp_client_DataReceived(object sender, Rtsp.RtspChunkEventArgs e)
      {
          // RTP Packet Header
          // 0 - Version, P, X, CC, M, PT and Sequence Number
          //32 - Timestamp
          //64 - SSRC
          //96 - CSRCs (optional)
          //nn - Extension ID and Length
          //nn - Extension header

          int rtp_version =      (e.Message.Data[0] >> 6);
          int rtp_padding =      (e.Message.Data[0] >> 5) & 0x01;
          int rtp_extension =    (e.Message.Data[0] >> 4) & 0x01;
          int rtp_csrc_count =   (e.Message.Data[0] >> 0) & 0x0F;
          int rtp_marker =       (e.Message.Data[1] >> 7) & 0x01;
          int rtp_payload_type = (e.Message.Data[1] >> 0) & 0x7F;
          uint rtp_sequence_number = ((uint)e.Message.Data[2] << 8) + (uint)(e.Message.Data[3]);
          uint rtp_timestamp = ((uint)e.Message.Data[4] <<24) + (uint)(e.Message.Data[5] << 16) + (uint)(e.Message.Data[6] << 8) + (uint)(e.Message.Data[7]);
          uint rtp_ssrc =      ((uint)e.Message.Data[8] << 24) + (uint)(e.Message.Data[9] << 16) + (uint)(e.Message.Data[10] << 8) + (uint)(e.Message.Data[11]);

          int rtp_payload_start = 4 // V,P,M,SEQ
                              + 4 // time stamp
                              + 4 // ssrc
                              + (4 * rtp_csrc_count); // zero or more csrcs

          uint rtp_extension_id = 0;
          uint rtp_extension_size = 0;
          if (rtp_extension == 1)
          {
              rtp_extension_id = ((uint)e.Message.Data[rtp_payload_start + 0] << 8) + (uint)(e.Message.Data[rtp_payload_start + 1] << 0);
              rtp_extension_size = ((uint)e.Message.Data[rtp_payload_start + 2] << 8) + (uint)(e.Message.Data[rtp_payload_start + 3] << 0);
              rtp_payload_start += 4 + (int)rtp_extension_size;  // extension header and extension payload
          }

to get the eventId and endofEvent and such things.
Since you must be having better knowledge

What all you say?

**Comment by RogerHardiman** [comment]
The RTSP standard is for video. It does not have fields for Event ID, EndOfEvent, EventDuration etc.

Can you tell us more about what you are trying to do please and the server you are trying to connect to.

**Comment by TryyingToCode** [comment]
actually i will be working for RTSP shortly, as of now trying to detect the DTMF in RTP packet and i saw the dissection in "private void Rtsp_client_DataReceived", we can add functionality to get the Event ID, EndOfEvent, EventDuration etc.... like this might be ...
  
                      // the DTMF key pressed or released. 
                       DTMF_Event = DtmfPayload >> 24; 

                      // the "end" bit. 
                       DTMF_E = (DtmfPayload >> 23) & 0x01; 

                      // reserved bit - not used. 
                       DTMF_R = (DtmfPayload >> 22) & 0x01; 

                      // the DTMF power level (volume). 
                       DTMF_Volume = (DtmfPayload >> 16) & 0x3f; 

                      // tone duration. 
                       DTMF_Duration = DtmfPayload & 0xffff;

**Comment by RogerHardiman** [comment]
The 'payload start' tells you where in the RTP packet the DtmfPayload is located.
That should be where the RFC 4733 DTMF data is located and then you can use the shifting and AND functions.

**Comment by TryyingToCode** [comment]
can you tell me what codes need to be added after this to get the `          int rtp_version =      (e.Message.Data[0] >> 6);
          int rtp_padding =      (e.Message.Data[0] >> 5) & 0x01;
          int rtp_extension =    (e.Message.Data[0] >> 4) & 0x01;
          int rtp_csrc_count =   (e.Message.Data[0] >> 0) & 0x0F;
          int rtp_marker =       (e.Message.Data[1] >> 7) & 0x01;
          int rtp_payload_type = (e.Message.Data[1] >> 0) & 0x7F;
          uint rtp_sequence_number = ((uint)e.Message.Data[2] << 8) + (uint)(e.Message.Data[3]);
          uint rtp_timestamp = ((uint)e.Message.Data[4] <<24) + (uint)(e.Message.Data[5] << 16) + (uint)(e.Message.Data[6] << 8) + (uint)(e.Message.Data[7]);
          uint rtp_ssrc =      ((uint)e.Message.Data[8] << 24) + (uint)(e.Message.Data[9] << 16) + (uint)(e.Message.Data[10] << 8) + (uint)(e.Message.Data[11]);

          int rtp_payload_start = 4 // V,P,M,SEQ
                              + 4 // time stamp
                              + 4 // ssrc
                              + (4 * rtp_csrc_count); // zero or more csrcs

          uint rtp_extension_id = 0;
          uint rtp_extension_size = 0;
          if (rtp_extension == 1)
          {
              rtp_extension_id = ((uint)e.Message.Data[rtp_payload_start + 0] << 8) + (uint)(e.Message.Data[rtp_payload_start + 1] << 0);
              rtp_extension_size = ((uint)e.Message.Data[rtp_payload_start + 2] << 8) + (uint)(e.Message.Data[rtp_payload_start + 3] << 0);
              rtp_payload_start += 4 + (int)rtp_extension_size;  // extension header and extension payload
          }`

DTMF event and end of event etc

**Comment by RogerHardiman** [comment]
So
   uint DtmfPayload = e.Message.Data[rtsp_payload_start];

Then you will use the bitwise operations eg >> and & from your code.

**Comment by TryyingToCode** [comment]
Hey i was not able to get the DTMF event using my code, if you know, how to get it using the bitwise operation, can you provide me the code.
`// the payload data is 4 bytes as per RFC 2833 (see section 3.5) 
                 // 
                 //    0                   1                   2                   3 
                 //    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 
                 //   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 
                 //   |     event     |E|R|  volume    |          duration            | 
                 //   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 
                 // 
                 //               Figure 1: Payload Format for Named Events 
                 // `

**Comment by RogerHardiman** [comment]
None of us have written code to process RTP packets containing DTMF data.
So we cannot help.

Could you post a dump of the RTP Packet in Hex and the code do carry out the bitwise operations and I can see if I can spot something.

**Comment by TryyingToCode** [comment]
can you share your mail id? or mail me on cloverobert@gmail.com
I hope that works

**Comment by RogerHardiman** [comment]
Actually the easiest place is to post it here on github. You can attach files to the post too.

**Comment by TryyingToCode** [comment]
> Frame 3351: 62 bytes on wire (496 bits), 62 bytes captured (496 bits)
    Encapsulation type: Ethernet (1)
    Arrival Time: Nov 17, 2017 20:20:22.296116000 India Standard Time
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1510930222.296116000 seconds
    [Time delta from previous captured frame: 0.000085000 seconds]
    [Time delta from previous displayed frame: 0.000085000 seconds]
    [Time since reference or first frame: 32.981240000 seconds]
    Frame Number: 3351
    Frame Length: 62 bytes (496 bits)
    Capture Length: 62 bytes (496 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:rtp:rtpevent]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: IntelCor_ea:05:d3 (e4:a4:71:ea:05:d3), Dst: DragonPa_30:49:e4 (b8:c1:a2:30:49:e4)
    Destination: DragonPa_30:49:e4 (b8:c1:a2:30:49:e4)
    Source: IntelCor_ea:05:d3 (e4:a4:71:ea:05:d3)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 192.168.1.4, Dst: 123.252.233.226
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
    Total Length: 48
    Identification: 0x111f (4383)
    Flags: 0x00
    Fragment offset: 0
    Time to live: 128
    Protocol: UDP (17)
    Header checksum: 0x0213 [validation disabled]
    [Header checksum status: Unverified]
    Source: 192.168.1.4
    Destination: 123.252.233.226
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
User Datagram Protocol, Src Port: 13886, Dst Port: 27240
    Source Port: 13886
    Destination Port: 27240
    Length: 28
    Checksum: 0x8305 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 17]
Real-Time Transport Protocol
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 .... = Extension: False
    .... 0000 = Contributing source identifiers count: 0
    0... .... = Marker: False
    Payload type: DynamicRTP-Type-101 (101)
    Sequence number: 31896
    Timestamp: 526226990
    Synchronization Source identifier: 0x3efc2765 (1056712549)
RFC 2833 RTP Event
    Event ID: Unknown (227)
    0... .... = End of Event: False
    .0.. .... = Reserved: False
    ..00 1011 = Volume: 11
    Event Duration: 11889
	
0000   b8 c1 a2 30 49 e4 e4 a4 71 ea 05 d3 08 00 45 00  ...0I...q.....E.
0010   00 30 11 1f 00 00 80 11 02 13 c0 a8 01 04 7b fc  .0............{.
0020   e9 e2 36 3e 6a 68 00 1c 83 05 80 65 7c 98 1f 5d  ..6>jh.....e|..]
0030   96 2e 3e fc 27 65 e3 0b 2e 71 9c c8 ed 4d        ..>.'e...q...M

**Comment by RogerHardiman** [comment]
thread has gone dormant so closing
