### ISSUE TITLE
Play message in RtspClientExample is missing authorization

### ISSUE THREAD

**Issue by graspergazon** [ngraziano/SharpRTSP#32]
Hi Nicolas,
Thank you for sharing this great library!

It seems like there is a small error in the RtspClientExample . I have an AXIS IP camera which requires user/pwd authorization. The example code was giving me a 401 error after sending the PLAY request. 

I added a "digest_authorization" string to the "play_message" header and now it works perfectly.

**Comment by RogerHardiman** [comment]
Hi
I've added new code to the library recently.
Can you tell me if the code changes work with your Axis camera for authorisation or if I still need to do something in the PLAY request.
Thanks

**Comment by manishjh** [comment]
Hi Kasper,
Could you please point to the changes you made, I am facing the exact same issue. 
Thanks,

**Comment by RogerHardiman** [comment]
Added a fix in January last year and no new feedback given
