### ISSUE TITLE
Rtsp Basic authorisation

### ISSUE THREAD

**Issue by ziza69** [ngraziano/SharpRTSP#33]
If camera supportst only "Basic" authorisation, RtspClientExample does not work. You should check for "Basic" in Rtsp_MessageReceived (message looks like: "WWW-Authenticate: Basic realm="xxxxxxx"...). We could extend 'GenerateDigestAuthorisation' like this:
`       // Generate Digest Authorization
        public string GenerateDigestAuthorization(string username, string password,
            string realm, string nonce, string url, string command, bool basic)  {

            if (username == null || username.Length == 0) return null;
            if (password == null || password.Length == 0) return null;
            if (realm == null || realm.Length == 0) return null;
            if (basic == true) return ("Basic " + System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(username + ":" + password)));`

**Comment by RogerHardiman** [comment]
Are you able to put a camera online with basic authorisation that I can test with. All the cameras I have here use Digest. Really the Basic mode is bad as the password is easy to extract from a wireshark log.
But I am adding the feature into RTSPClient right now.
Roger

**Comment by RogerHardiman** [comment]
I have added in Basic Authorization to RTSPClientExample but it needs testing.
