### ISSUE TITLE
Authorization and setup

### ISSUE THREAD

**Issue by arc95** [ngraziano/SharpRTSP#34]
Hi @ngraziano. Thanks for this great library! I have the following use case and wondering where to start:

1. User selects a CCTV RTSP video stream.
2. We authenticate against that camera with username/password.
3. Return stream to the user's browser via WebAPI.
4. User can play the stream in an HTML5 `video` player. 

Is this possible with SharpRTSP? Thanks.

**Comment by RogerHardiman** [comment]
You want to look for some other open source projects that convert RTSP to WebRTC format.
Then you can play the video with most web browsers which now support WebRTC format.
