### ISSUE TITLE
Sending RGB images

### ISSUE THREAD

**Issue by RTlukas** [ngraziano/SharpRTSP#35]
Hi,

I try to send the stream of a local webcam. To do so, I converted every image from RGB to YUV an stored the resulting picture in a byte array. I used the resulting array to replace the suv_data byte array from the RTSPCameraExample to send this via the rtsp stream.
When I open the resulting stream the image doesn't seem to be the original image.
Is there any problem when converting rgb images and use them for the stream?

**Comment by RogerHardiman** [comment]
Hi there
There are a few things to check
a) when you used the original RTSPCameraExample (with my Test Image) did that play OK in your viewing software   [this just tells us everything works before we make some changes]
b) when you convert your RGB to YUV, do you know which YUV format you are converting too. (there are formats like YUV420, NV12, NV21 etc. They are all different layouts of the Y, U and V pixels.
c) have you told the CameraExample what the new image size is (the example was pretty low resolution)
d) Check which H264 encoder the Camera Example is using. There is an h264 Encoder called 'Tiny' and a h264 encoder called 'simple'.   'Tiny' only works at one fixed resolution.

Finally if you want a quick test, copy all the Green Pixels into the Y data of the YUV and then set the U day to 127 and the V data to 127. You'll have a nice monochrome image but can see if it works.

**Comment by RTlukas** [comment]
a) the test image works properly
b) I'm not quite sure what format I am using. The problem is that I searched for RGB to YUV converter. The formular that I got, returned an Y U V - value for each pixel, which doesn't seem to be correct when I look at YUV420 format
c) I didn't change the resolution. Even if I use the wrong resolution I should be able to see a part of the original picture, shouldn't I ?
d) I'm using the simple encdoer

Which format does the yuv_value byte array, which is used to create the stream, should have?
I think this format is the problem in my case, because the picture I get when I use your "green-approach" is not a correct one. The example picture is the resulting picture from the stream. There should be a romm with a calendar in it.
![example](https://user-images.githubusercontent.com/38726867/39352872-54f8d020-4a06-11e8-87f1-691827cb2390.PNG)

**Comment by RogerHardiman** [comment]
Hi
The 'Simple H264 encoder' uses YUV420.
If you have a YUV picture of size 352x288 it will be stored in a yum byte array as 3 blocks of data.
The first block of data is the Y data and is 101376 bytes. The next block of data is the U data which is 25344 and the last block of data is the V data which is 25344.
You will see that the U and V data store less data.
So when you convert RGB to YUV there will be times you add the Y and the U and the V into the yuv_byte_array. There will be times when you only and the Y data to the yuv_byte_array and you throw away the U and V data.

In the TestCard code you'll see this
```
        // YUV size
        int y_size = width * height;
        int u_size = (width >> 1) * (height >> 1);
        int v_size = (width >> 1) * (height >> 1);
        yuv_frame = new byte[y_size + u_size + v_size];
```

If you want a quick test then
1) Convert RGB to YUV. Place the Y data into the right part of the yuv_buffer
2) Then fill the U data in the yuv_buffer with '127'.
3) Then fill the V data in the yuv_buffer with '127'

You should see your room, but in monochrome.

Then you can write some extra code to fill the U data and V data correctly.
The proper name for the U and V data is 'sub-sampled' U and V planes.


Roger
