### ISSUE TITLE
Unable to playback rtsp streams using 3rd party players

### ISSUE THREAD

**Issue by mbullock976** [ngraziano/SharpRTSP#36]
Hi

This is a great project and has helped me begin to learn the concepts of Rtsp server especially around the messaging.

My colleague and I are both looking at using this project to see if we can host our external ffmpeg encoded h264 stream, and have 3rd party players also, to playback this stream.

We can playback our h264 stream using the RtspClientExample and using ffplay to play the output .264 file.

But we cannot playback PULL stream using 3rd party players such as VLC or ffmediaElement as we need to have a solution that allows any client including 3rd partys to playback the stream.

This is my ffmpeg code:

 .\ffmpeg -protocol_whitelist file,udp,rtp -re  -i camera99.sdp -vcodec copy  -muxdelay 0.1 -threads 4 -sc_threshold 0 -rtsp_transport udp -f rtsp  rtsp://127.0.0.1:8554/PUSH/myStream

I don't know how to playback this stream using 3rd party players such as VLC or ffmediaElement ??

**Comment by RogerHardiman** [comment]
Hi
I think Nicolas was adding some PUSH support but I've not used that bit of the library.

What I've done with the library on my own projects is 
a) Take the RTSPCameraExample
b) Modify it to use ffmpeg via its 'C API' to feed it YUV images and get back H264 NALs.
c) Send out the NALs to RTSP clients from RTSPCameraExample. The clients just connect to rtsp://127.0.0.1/video

**Comment by mbullock976** [comment]
@RogerHardiman thanks, but would that mean we would be limited to using the client example here or writing custom code, to playback the stream.

Ideally what we need is a rtsp server solution, where we can host our external h264/rtp streams but be able to use both, custom written rtsp clients, but also playback using well known rtsp clients such as VLC with writing custom code for the client side
