### ISSUE TITLE
Is SharpRTSP support sending Receiver Report in UDP protocol?

### ISSUE THREAD

**Issue by sinhngoc2008** [ngraziano/SharpRTSP#42]
I'm using sharprtsp lib to build an application that consumes video from VLC RTSP server.
I cannot send a correct Receiver Report to VLC server to keep the connection alive more than one minute.
Please help me to solve it

**Comment by RogerHardiman** [comment]
I added some code to send Receiver Reports and it is in the RtspClientExample.
But it may have bugs in and it only sends an empty Receiver Report.

Do you have an example VLC command line which starts the VLC RTSP Server so I can set up a test here in my office?

Thanks

**Comment by sinhngoc2008** [comment]
This is the vlc command to start a VCL RTSP Server:
cvlc -vvv --rtsp-tcp video.mkv  :sout=#rtp{sdp=rtsp://192.168.0.16:8554/test} :no-sout-all :sout-keep --loop --ttl 1

or you can set up on the VLC GUI
https://support.spinetix.com/wiki/Tutorial:Streaming_using_VLC

The VLC RTSP Server provides the RTCP packets on the UDP protocol
Also, the SDP parser of your project is not correct in this case.

Please check it!

**Comment by RogerHardiman** [comment]
I have found the SDP parsing issue - Unsigned Int64 needed for Origin.

Now I have problems getting the SETUP command to work.

I'll need to find out what is wrong before I can look at the Receiver Report problem.

(I assume you have found and fixed these issues to get to the point where the Receiver Report has an error. Would you like to share the fixes you have done already?)

Thanks

**Comment by RogerHardiman** [comment]
Ok. I've got UDP streaming working. I receive the stream. On my setup it seems to stop after 10 or 15 seconds. So I've got something to work with.

I'm away this weekend so may be able to take a look some time next week.

**Comment by ngraziano** [comment]
I have change the RTSP keep alive from OPTIONS to GET_PARAMETER in commit 7529bd6.

For me it make VLC happy until the end of a file of more than 5 min, but the loop does not work.

The send of RTCP report in UDP is not implemented, we have to save the port number at SETUP response (and maybe source address) and create a dedicated UdpClient.

**Comment by RogerHardiman** [comment]
I've added another change to the RTSP Client Example.
If the camera does not support GET_PARAMETER then it falls back to using OPTIONS

But as @ngraziano said, to send UDP RTCP RR Receiver Reports will require some additional code.
We always welcome submissions from other developers

**Comment by ikriz** [comment]
Also Interested in the RTP over UDP implementation for the RTSP server, any indication when this may be implemented? Willing to spend some time on it just dont know where to start...

**Comment by ngraziano** [comment]
Old bug report. I think all problem have been fixe so I close it.
