### ISSUE TITLE
make "describeResponse" available as member

### ISSUE THREAD

**Issue by ChristophKrause** [ngraziano/SharpRTSP#55]
Within describeResponse the SDP is read and parsed.

I see no way to get o not parsed information.

For example: I need the of 
a=framerate:XX
because the fr is not always provided with the SPS

**Comment by winkmichael** [comment]
You can already get the SDP as a string, just pop it through this lib.

https://github.com/clux/sdp-transform

**Comment by 3Passer** [comment]
thanks for the link.
parsing is not the problem, but getting the sdp string with making a second connection to the source is something i do  not really like.

But i do not see a ways with the current verison of this lib.

**Comment by ngraziano** [comment]
The SDP is in the message response of DESCRIBE. 
You can access in Data propertie.
See https://github.com/ngraziano/SharpRTSP/blob/master/RtspClientExample/RTSPClient.cs#L706 for an exemple. `System.Text.Encoding.UTF8.GetString(message.Data)` allow to get it as string.

**Comment by 3Passer** [comment]
I am using custom.

This is to receive Axis RTSP Streams, they do not offer framerate with the sps.

Am I overlooking something? 
How can I set the Rtsp_MessageReceived event. 
In my implementation I have the following lines
`sing (var rtspClient = new RtspClient(connectionParameters)) {
					rtspClient.FrameReceived += receiveFrame;
...`
As far as I can see this event is offered only internal :(

**Comment by winkmichael** [comment]
Not all cameras include the FPS value in the SDP.

**Comment by ngraziano** [comment]
RTSPClient.cs is an example of client, feel free to modify it after copying it to your project.

Around line 706 , you can store the SDP in a new global property of your version of RTSPClient class. 
You can also create a new event and call it around same line to notify the receive of the SDP.

If your modification are interesting for other you can create a pull request after that.

**Comment by 3Passer** [comment]
Ill take a look at this and will do some modifications .

thx for the advise
