### ISSUE TITLE
VLC Server Test

### ISSUE THREAD

**Issue by rossbuggins** [ngraziano/SharpRTSP#58]
Looking at the RtspClientExample it shows a test url of:

>             // VLC Server Tests
>             // String url = "rtsp://192.168.1.150:8554/test";

Could you let me know how you have VLC server configured at the command line to allow the connection please?

**Comment by RogerHardiman** [comment]
1) Open VLC
2) On the Mac I get a window with LIBRARY, MY COMPUTER, LOCAL, NETWORK and INTERNET
3) Select LIBRARY->PLAYLIST->OPEN MEDIA
4) The 'Open Source' window appears
5) At the top of this window is File/Disc/Network/Capture.
6) Pick Network. There is a URL box. Type in   rtsp://user:password@192.168.1.99:8554    (change to your IP address) and pick OPEN
7) The RTSP url now appears in the Playlist. Click on the URL in the Playlist and click on the play triangle.

Note there is also the command line cvlc where you can give a RTSP url on the command line.
