### ISSUE TITLE
RTSP server streaming pictures 

### ISSUE THREAD

**Issue by aalmik** [ngraziano/SharpRTSP#59]
I have camera taking pictures to directory that I would like to stream.  How do I stream jpg files using your RTSP server implementation?

I like very much of your RTSP client and server library. Camera sample works nicely with VLC player.

**Comment by RogerHardiman** [comment]
Unfortunately there is nothing in the code to read a folder of JPEGs and stream them.
You could try and adapt the Camera Example. You'll need to read the JPEGs, decompress them, convert the image into YUV format and then feed the simple H264 encoder but the bandwidth will be very high.
