### ISSUE TITLE
(Not issue) Suggestion to use different h264 encoder

### ISSUE THREAD

**Issue by mattewre** [ngraziano/SharpRTSP#64]
Hello,
I am using ShartRTSP to create an RTSP server.
RtspCameraExample works out-of-the-box: it is nice and clear.

About encoders:
- Tiny: resolution limited to 192x128
- Simple: lossless and seems to create too large UDP dataframe with higher resolution, so it fails. 
`UDP Write Exception System.Net.Sockets.SocketException (0x80004005): A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself`

Therefore I would like to use it with a lossy h264 encoder on Windows, but I don't know what to look for or how to do.
Any suggestions / examples / suggested libraries / Nugets / documents to read about?

Thank you

**Comment by RogerHardiman** [comment]
Hi
Trying to catch up on Issue Reports.

I use FFMPEG.Autogen to provide a C# interface to ffmpeg. I then use an ffmpeg build with libx264 included. That gives me a good h264 encoder for use with Sharp RTSP

Roger
