### ISSUE TITLE
How to connect to IP camera over GSM

### ISSUE THREAD

**Issue by weedkiller** [ngraziano/SharpRTSP#65]
Hello we have an LTE connection, how do we connect and capture the stream

**Comment by RogerHardiman** [comment]
There is insufficient detail in your question to give you a proper answer.
But here are some pointers.
If you can reach the IP Address of the camera, then get the camera's RTSP URL and use that to receive the video.
The camera manufacturer will give you the RTSP URL. They all vary from camera to camera.
If the LTE connection does not allow you to connect to the camera directly (eg the carrier uses NAT) you will need to set up a VPN connection so you can reach the camera's IP address
