### ISSUE TITLE
How to replace YUV Image with Web Camera?

### ISSUE THREAD

**Issue by begone1992** [ngraziano/SharpRTSP#66]
Hi, 

I am trying to use "RTSPCameraExample" with my default web camera. The RTSP technology is something new to me, so can I ask you to explain how can I replace YUV Image (test card) with my Web Camera?

Thank you,

**Comment by RogerHardiman** [comment]
you would have to use some other library to open the USB camera device and get images. They would probably be in a different YUV format (a different order of the pixels in the data buffer) so you'd need to convert them before passing into the simple h264 encoder.   You'd be better looking at a 3rd party yuv conversion library and encoding library like libav
