### ISSUE TITLE
Recording Format

### ISSUE THREAD

**Issue by lkinfotechai** [ngraziano/SharpRTSP#71]
i am testing with h265 rtsp stream and i want to record video+audio in different formats like
.ts
.asf
.mp4
.avi
how i can do this recording audio+video both in the above mentioned formats.

**Comment by RogerHardiman** [comment]
Each file format needs a load of software to correctly make that file type with all the right data and payload contents.
That is too much for SharpRTSP to do (and it has been done by other libraries) so you have to look elsewhere for file writers.

In my own projects I have used ffmpeg (via a C# wrapper) to write .mp4 files.
I've also made Interop libraries around Google's open source MP4 writing library in the past and called it from C#

Roger
