### ISSUE TITLE
Add H265 and MJPEG support

### ISSUE THREAD

**Issue by REPRESSION** [ngraziano/SharpRTSP#73]
Hello,

I am Gabriel from Obvious Technologies company. 
We are interested in using your library as a client and server in our solution, but need H264, H265 and MJPEG support.

Would you be interested in adding H265 and MJPEG support to your client and server if we paid for the development ?

Regards,
Gabriel

**Comment by RogerHardiman** [comment]
H265 support is already in the client.

Adding to the MJPEG or adding H265 to the server and the client can be done and the offer of paid development is great. At the current time I don't have any spare time to take on any additional work.

**Comment by nguyenthaohut** [comment]
> H265 support is already in the client.
> 
> Adding to the MJPEG or adding H265 to the server and the client can be done and the offer of paid development is great. At the current time I don't have any spare time to take on any additional work.

please contact to me by email to nguyenthaohut@gmail.com. we can disccuss about the paid development

**Comment by ngraziano** [comment]
MJPEG added to client in 1.2.0

**Comment by nahueltaibo** [comment]
Hi ngraziano, is there any documentation or examples on how work with mjpeg frames?

**Comment by ngraziano** [comment]
Hi,
@nahueltaibo you can look at the [RtspClientExample](https://github.com/ngraziano/SharpRTSP/tree/dotnetcore/RtspClientExample) for use of MJPEG frame. 
On an mjpeg stream all the frame are save as JPEG files.

Please use discussions tab  of github for this kind of help request, the next time.
