### ISSUE TITLE
TestCard MJPG example

### ISSUE THREAD

**Issue by carlberg74** [ngraziano/SharpRTSP#80]
New to this library.
Is there some example showing how to use mjpg frames or similar encoding.
Trying to use OpenCV and read webcam frames and then stream that with this library.. 

Trying to convert mjpg to h264/h265 and use that with this library, but converting mjpg to h264/h265 seem difficult in it self..

anyone?

Cheers
-Anders

**Comment by ngraziano** [comment]
The conversion from mjpg to h264 is not in the scope of this library.
