### ISSUE TITLE
README File: Spelling Mistakes Correction

### ISSUE THREAD

**Issue by abdullahfarwees** [ngraziano/SharpRTSP#86]
1. 
RTP Receiver - will **recieve** RTP and RTCP packets and pass them to a transport handler
Change **recieve** to **receive**

2.
STEP 5 - Handle RTP Video - This code handles each incoming RTP packet, combining RTP packets that are all part of the same frame of **vdeo** (using the Marker Bit).
Change **vdeo** to **video**

3.
Transport Handler - Transport **hanlders** for H264, H265/HEVC, G711 and AMR are provided.
Change **hanlders** to **handlers**

**Comment by abdullahfarwees** [comment]
Raised a [PR #87](https://github.com/ngraziano/SharpRTSP/pull/87) after correcting the above.

**Comment by ngraziano** [comment]
#87 merged 
thanks
