### ISSUE TITLE
repo is behind NuGet package

### ISSUE THREAD

**Issue by bentorkington** [ngraziano/SharpRTSP#89]
Thanks for you work on this, and for publishing it as a NuGet package - very helpful!

When porting my app to use the new NuGet package, I noticed a few member names have been updated, but the latest commit on the master branch doesn't reflect this. Any chance you could update the repo to the latest? Thanks!

**Comment by ngraziano** [comment]
Hi,

The source of the nuget package is in the branch [donetcore](https://github.com/ngraziano/SharpRTSP/tree/dotnetcore).
I will add a comment in the README for that.

**Comment by bentorkington** [comment]
I see, thank you. Until then, maybe consider changing the default branch to `dotnetcore`, or renaming it to `main` and retiring `master`?
