### ISSUE TITLE
Update NuGet package please?

### ISSUE THREAD

**Issue by bentorkington** [ngraziano/SharpRTSP#92]
I have a problem with `UDPSocket.cs` logging "Received RTSP data on port..." every packet which makes debugging other things in my app hard.

I see you've already deleted the offending `Console.Log` line. Any chance you could push an update to NuGet sometime?

**Comment by ngraziano** [comment]
I have update the nuget  package (1.1.0) with the last commit in dotnetcore.

**Comment by bentorkington** [comment]
Merci!
